package ds_array;
import ds_array.arranjo.Lista;

/**
@author: Marllos Prado.
Classe para testar os exercícios 6, 7 e *8* (obs.: 8 usando o metodo *uneListas*).

Class to test exercises 6, 7 and *8* (Note: 8 using the *uneListas* method).
*/

public class TestaLista2 {
  public static void main (String[] args) {
	int capacidadeMaxima = 12;
    Lista lista = new Lista(capacidadeMaxima);
    Integer n = null;
	
	Integer kC = new Integer(3);
	Integer kE = new Integer(5);
	
	/*Insere o item kC e kE na lista. Depois:
	    - Insere um novo item após uma chave existente com o método insereAposChave.
		- Insere um item que ainda não existe com o método insereSemRepetir.
		- Insere um item que já existe com o método insereSemRepetir.
	
	Inserts the item kC and kE into the list. Later:
	- Inserts a new item after an existing key with the insereAposChave method.
	- Inserts an item that does not yet exist with the insereSemRepetir method.
	- Inserts an item that already exists with the insereSemRepetir method.
	*/
	try {
	  lista.insere(kE);  
	  lista.insere(kC); 
	  lista.insereAposChave(new Integer(50), kE);
	  lista.insereSemRepetir(new Integer(90));
	  System.out.println("Chegou ate aqui sem excecao! Sinal de que as insercoes funcionaram!");
	  lista.insereSemRepetir(new Integer(3));
	} catch (Exception e) {
	  System.out.println(e.getMessage());
	}
	
	
	//Testa metodo que une duas listas
	//Testing method that joins two lists
	
	Lista L1 = new Lista(3);
	Lista L2 = new Lista(2);
	
	// variavel que irá guardar a referencia para a lista que será gerada pela união de L1 e L2.
	// variable that will store the reference to the list that will be generated by the union of L1 and L2.
	Lista L3 = null; 
	
    Integer itemA = new Integer(2);
	Integer itemB = new Integer(3);
	Integer itemC = new Integer(4);
	
	Integer itemD = new Integer(7);
	Integer itemE = new Integer(8);
	
	
	try {
      
	  // Insere cada objeto Integer criado nas listas L1 e L2
      // Insert each created Integer object into L1 and L2 lists
      L1.insere(itemA);
      System.out.println("Inseriu na L1 " + itemA.toString());
	  L1.insere(itemB);
      System.out.println("Inseriu na L1 " + itemB.toString());
	  L1.insere(itemC);
      System.out.println("Inseriu na L1 " + itemC.toString());
	  
	  L2.insere(itemD);
      System.out.println("Inseriu na L2 " + itemD.toString());
	  L2.insere(itemE);
      System.out.println("Inseriu na L2 " + itemE.toString());
	
	  
	  //Chama o método que une a L2 na L1 e armazena o retorno em L3
	  //Call the method that joins L2 to L1 and stores the return in L3 
	  L3 = L1.uneListas(L2);
	  
	  //Testa se L3 tem o tamanho igual a L1 + L2. Se tiver, é porque ela de fato uniu os itens de L1 e L2.
	  //Test if L3 is the same size as L1 + L2. If so, it's because she actually merged the items from L1 and L2.
	  System.out.println("O tamanho de L3 eh: "+L3.getTamanho());
	  
	  
	}catch(Exception e) {
	  System.out.println(e.getMessage());
	}
 
  }
}
